#vm-deployment.yml

parameters:

- name: serviceId
  type: string
  
- name: serviceConnection
  type: string

- name: deploymentType
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy Shir Virtual Machine Extension in ${{ parameters.serviceId }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
                    "Starting az deployment"
                    az deployment sub $(deploymentType) --location 'australiaeast' `
                    --name $(deploymentName) `
                    --template-file $(System.ArtifactsDirectory)\content\bicep-templates\deployment\deployment-templates\deploy-ShirExtension.bicep `
                    --parameters $(System.ArtifactsDirectory)\content\bicep-templates\deployment\12-ShirExtension\shirextension-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json `                  
                    --parameters owner='$(Owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)' `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)'


   