#deploy-NetworkPeering-Global.yml

parameters:
- name: serviceName
  type: string

- name: serviceConnection
  type: string
  
- name: deploymentType
  type: string

- name: serviceId
  type: string

- name: landingZoneType
  type: string

- name: subscriptionID
  type: string

steps:
  - task: AzureCLI@2
    displayName : Global Peering between ${{parameters.serviceName}} Hub
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --parameters localVirtualNetworkSubscriptionId=${{ parameters.subscriptionID }} `
                    --parameters remoteVirtualNetworkSubscriptionId=${{ parameters.subscriptionID }} `
                    --template-file $(System.ArtifactsDirectory)\$(bicep-deployment-templates)\deploy-HubToHubVnetPeering.bicep `
                    --parameters $(System.ArtifactsDirectory)\$(deployments)\$(landingZoneType)\parameter-files\${{ parameters.serviceId }}\02-Network\Peering-HubToHub-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json