#deploy-EnableResourceProvides.yml

parameters:

- name: serviceName
  type: string

- name: serviceConnection
  type: string

steps:
  - task: AzureCLI@2
    displayName : Enable Resource Providers in ${{ parameters.serviceName }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: bash $(System.ArtifactsDirectory)\$(scripts)\EnableResourceProviders.sh