#deploy-NetworkPeering.yml

parameters:

- name: serviceId
  type: string
  
- name: serviceConnection
  type: string

- name: subscriptionId
  type: string

- name: deploymentType
  type: string

- name: connectivitySubscServiceConnection
  type: string

- name: connectivitySubscriptionId
  type: string

steps:
  - task: AzureCLI@2
    displayName : Hub To ${{parameters.serviceId}} Spoke Virtual Network Peering
    inputs:
      azureSubscription: ${{ parameters.connectivitySubscServiceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --parameters remoteVirtualNetworkSubscriptionId='${{ parameters.subscriptionId }}' `
                    --template-file $(templateDirectory)\deployment-templates\deploy-HubToSpokeVnetPeering.bicep `
                    --parameters $(parameterDirectory)\02-Network\Peering-HubtoSpoke.param.$(AzureEnvironmentPrefix).json

  - task: AzureCLI@2
    displayName : ${{parameters.serviceId}} Spoke to Hub Virtual Network Peering
    inputs:
      azureSubscription: ${{ parameters.serviceConnection}}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --parameters remoteVirtualNetworkSubscriptionId='${{ parameters.connectivitySubscriptionId }}' `
                    --template-file $(templateDirectory)\deployment-templates\deploy-SpokeToHubVnetPeering.bicep `
                    --parameters $(parameterDirectory)\02-Network\Peering-SpokeToHub.param.$(AzureEnvironmentPrefix).json
