#deployNsgRules.yml

parameters:

- name: serviceId
  type: string

- name: serviceConnection
  type: string

- name: deploymentType
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy NSG Rules in ${{ parameters.serviceId }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(System.ArtifactsDirectory)\content\bicep-templates\deployment\deployment-templates\deploy-NsgRule.bicep `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)' `
                    --parameters $(System.ArtifactsDirectory)\content\bicep-templates\deployment\07-Network\NsgRules.param.$(AzureEnvironmentPrefix).json