#deploy-storageAccount.yml

parameters:

- name: serviceName
  type: string

- name: serviceConnection
  type: string

- name: deploymentType
  type: string

- name: serviceId
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy Sftp Storage Account in ${{ parameters.serviceName }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
                    $sshPublicKey = az keyvault secret show --name "$(destSftpSshKeySecret)" --vault-name "$(keyVaultNameforSecret)" --query "value"
                    echo '*********************************************************'
                    echo 'sshkey is: ' $(destSftpSshKeySecret)
                    echo 'sshkeyValue is: ' $sshPublicKey
                    echo '************************************************************'
                    az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(System.ArtifactsDirectory)\content\bicep-templates\deployment\deployment-templates\deploy-SFTP.bicep `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)' `
                    --parameters owner='$(owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters appName='$(appName)' `
                    --parameters resourceLocation='$(resourceLocation)' `
                    --parameters sftpstorageAccountName='$(destStorageAccountName)' `
                    --parameters sftpRootContainerName='$(rootContainerName)' `
                    --parameters warrantyPeriod='$(warrantyPeriod)' `
                    --parameters sftpUserName='$(sftpUserName)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)' `
                    --parameters sshPublicKeyValue=$sshPublicKey `
                    --parameters $(System.ArtifactsDirectory)\content\bicep-templates\deployment\04-SFTP\sftp-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json

  - task: AzureCLI@2
    displayName : Add A Record in DNS Zone
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $location = "$(resourceLocation)"
        $storageAcct = "$(destStorageAccountName)"
        $endpoint = "pve-$location-$storageAcct"
        $dnsZoneGrp = "default"
        $rgName = "$(rgName)"

        az account set --subscription "$(subId)"
        $privateIp = az network private-endpoint dns-zone-group show --endpoint-name $endpoint -n $dnsZoneGrp -g $rgName --query privateDnsZoneConfigs[].recordSets[].ipAddresses[] --output tsv
        $privateIp

        az account set --subscription "$(connSubId)"
        az network private-dns record-set a list -g "$(connRg)" -z privatelink.blob.core.windows.net
        az network private-dns record-set a add-record -g "$(connRg)" -a $privateIp -n $storageAcct -z privatelink.blob.core.windows.net
