parameters:
    name: ''
    displayName: ''
    pool: ''
    continueOnError: ''
    emailSubject: ''
    emailBody: ''
    dependsOn: ''
    environment: ''
    condition: ''
    variableGroup: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName}}
  pool: ${{ parameters.pool }}
  continueOnError: ${{ parameters.continueOnError}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  variables:
  - group: ${{ parameters.variableGroup}}
  steps:
  - task: GraphEmail@0
    displayName: 'Sending email using Graph Api'
    inputs:
      To: $(npDefaultReceiverEmail)
      From: $(npFromEmail)
      Subject: ${{ parameters.emailSubject}}
      Body: ${{ parameters.emailBody}}
      BodyAsHtml: true
      ShowClientSecret: false
      ClientID: $(npClientId)
      ClientSecret: $(npClientSecret)
      TenantDomain: $(npTenantDomain)
      condition: eq(variables.environment, 'Non-Production')
  - task: GraphEmail@0
    displayName: 'Sending email using Graph Api'
    inputs:
      To: $(prdDefaultReceiverEmail)
      From: $(prdFromEmail)
      Subject: ${{ parameters.emailSubject}}
      Body: ${{ parameters.emailBody}}
      BodyAsHtml: true
      ShowClientSecret: false
      ClientID: $(prdClientId)
      ClientSecret: $(prdClientSecret)
      TenantDomain: $(prdTenantDomain)
    condition: eq(variables.environment, 'Production')
