parameters:
    stage: ''
    displayName: ''
    dependsOn: ''
    condition: ''
    pool: ''
    variableGroup: ''
    taskNumber: ''
    workItemState: ''
    workItemComment: ''
    updateWorkItemDescription: ''
    emailSubjectForPass: ''
    emailSubjectForFile: ''
    emailBodyForFile: ''
    environment: ''
    receiverEmailAddress: ''

stages:
- stage: ${{ parameters.stage}}
  displayName: ${{ parameters.displayName}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  variables:
    - name: keyVaultSecretValue
      value: $[ stageDependencies.download_key_vault_secret.get_kvsecret.outputs['get_kv_secret_value.KvSecretValue'] ]

  jobs:
  - template: updateworkitem.yml
    parameters:
      name: update_workitem
      displayName: ${{ parameters.updateWorkItemDescription}}
      pool:
        vmImage: 'windows-latest'
      continueOnError: false
      variableGroup: ${{ parameters.variableGroup}}
      scriptFilePath: 'CFS.Core.BKOF/scripts/UpdateWorkItem.ps1'
      dependsOn: ''
      workItemComment: ${{ parameters.workItemComment}}
      workItemId: ${{ parameters.taskNumber}}
      workItemState: ${{ parameters.workItemState}}

  - template: sendemail.yml
    parameters:
      name: send_email_via_ps_pass
      displayName: Send Email for Pass
      pool: ${{ parameters.pool}}
      continueOnError: false
      dependsOn:  update_workitem
      emailSubject: ${{ parameters.emailSubjectForPass}}
      emailBody: 'Please save the password. You will receive file information and username in a separate email. <br> Password: $(keyVaultSecretValue)'
      environment: ${{ parameters.environment}}
      receiverEmailAddress: ${{ parameters.receiverEmailAddress}}
      condition: ''
      variableGroup: var-password

  - template: sendemail.yml
    parameters:
      name: send_email_via_ps_file
      displayName: Send Email for File
      pool: ${{ parameters.pool}}
      continueOnError: false
      dependsOn:  update_workitem
      emailSubject: ${{ parameters.emailSubjectForFile}}
      emailBody: ${{ parameters.emailBodyForFile}}
      environment: ${{ parameters.environment}}
      receiverEmailAddress: ${{ parameters.receiverEmailAddress}}
      condition: ''
      variableGroup: var-password
