#deploy-Bastion.yml

parameters:

- name: serviceName
  type: string

- name: serviceConnection
  type: string

- name: deploymentType
  type: string
  
- name: serviceId
  type: string

- name: securitySubscriptionId
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy Bastion in ${{ parameters.serviceName }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(templateDirectory)\deployment-templates\deploy-Bastion.bicep `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)' `
                    --parameters owner='$(Owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)' `
                    --parameters $(System.ArtifactsDirectory)\bicep-templates\deployment\14-Bastion\Bastion-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json                    