#deploy-storageAccount.yml

parameters:

- name: serviceName
  type: string

- name: serviceConnection
  type: string

- name: deploymentType
  type: string

- name: serviceId
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy User-Assigned Managed Identity in ${{ parameters.serviceName }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(System.ArtifactsDirectory)\bicep-templates\deployment\deployment-templates\deploy-PrivateEndpointSQL.bicep `
                    --parameters workspaceSubscriptionId='$(securitySubscriptionId)' `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)' `
                    --parameters owner='$(Owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)' `
                    --parameters $(System.ArtifactsDirectory)\$(deployments)\10-PrivateEndpoints\pesql-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json