parameters:
    stage: ''
    displayName: ''
    dependsOn: ''
    condition: ''
    agentPool: ''
    keyVaultNameforSecret: ''
    zipFileSecretName: ''
    landingZoneServiceConnection: ''
    serviceAccountP: ''
    serviceAccountU: ''
    serviceAccountUE: ''
    vmName: ''
    tenantId: ''
    subId: ''

stages:
- stage: ${{ parameters.stage}}
  displayName: ${{ parameters.displayName}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  jobs:

  - template: getkvsecret.yml
    parameters:
      name: get_kvsecret
      displayName: 'Get KV Secret'
      agentPool: ${{ parameters.agentPool}}
      continueOnError: false
      keyVaultNameforSecret: ${{ parameters.keyVaultNameforSecret }}
      zipFileSecretName:  ${{ parameters.zipFileSecretName}}
      landingZoneServiceConnection: ${{ parameters.landingZoneServiceConnection }}
      serviceAccountUE: ${{ parameters.serviceAccountUE}}
      serviceAccountP: ${{ parameters.serviceAccountP}}
      serviceAccountU: ${{ parameters.serviceAccountU}}
      vmName: ${{ parameters.vmName}}
      tenantId: ${{ parameters.tenantId}}
      subId: ${{ parameters.subId}}
