parameters:
    stage: ''
    displayName: ''
    dependsOn: ''
    condition: ''
    pool: ''
    artifactName: ''
    variableGroup: ''



stages:
- stage: ${{ parameters.stage}}
  displayName: ${{ parameters.displayName}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  variables:
    - name: workItemId
      value: $[ stageDependencies.pre_stage.get_work_item_details.outputs['get_work_item.WorkItemId'] ]
    - name: workItemTag
      value: $[ stageDependencies.pre_stage.get_work_item_details.outputs['get_work_item.WorkItemTag'] ]
  jobs:

  - template: downloadandpublish.yml
    parameters:
      name: download_and_publish_excel_file
      displayName: 'Download and Publish Excel File to Artifacts'
      pool: ${{ parameters.pool}}
      continueOnError: false
      variableGroup: ${{ parameters.variableGroup}}
      scriptFilePath: 'CFS.Core.BKOF/scripts/DownloadWorkItemFile.ps1'
      artifactName: ${{ parameters.artifactName}}
      workItemId: $(workItemId)
      condition: eq(stageDependencies.pre_stage.get_work_item_details.outputs['get_work_item.WorkItemState'], 'To Do')

  - template: noattachmentemail.yml
    parameters:
      name: send_email_on_failure
      displayName: 'Send Email on failure downloading work item attachment'
      pool: ${{ parameters.pool}}
      continueOnError: false
      variableGroup: var-password
      dependsOn: download_and_publish_excel_file
      emailSubject: "Parameter File is missing for Task $(workItemId)"
      emailBody: '<p>Hi, </p> <p>Task $(workItemId) is missing a parameter file. </p> <p> This file is mandatory to initiate the extraction process. </p> <p> Please attach it to start the DMT Extraction process for Task $(workItemId).</p>'
      environment: $(workItemTag)
      condition: eq(dependencies.download_and_publish_excel_file.result, 'Failed')

  - template: updateworkitem.yml
    parameters:
      name: update_workitem_on_download_success
      displayName: 'Update Work Item on Successful Download of Attachment'
      pool: ${{ parameters.pool}}
      continueOnError: false
      variableGroup: ${{ parameters.variableGroup}}
      scriptFilePath: 'CFS.Core.BKOF/scripts/UpdateWorkItem.ps1'
      dependsOn: download_and_publish_excel_file
      workItemComment: "Successfully downloaded the input parameter file from work item: $(workItemId)"
      workItemId: $(workItemId)
      condition: eq(dependencies.download_and_publish_excel_file.result, 'Succeeded')
      workItemState: "In Progress"
      processed: 'true'

  - template: updateworkitem.yml
    parameters:
      name: update_workitem_on_download_failure
      displayName: 'Update Work Item on Failure Download of Attachment'
      pool: ${{ parameters.pool}}
      continueOnError: false
      variableGroup: ${{ parameters.variableGroup}}
      scriptFilePath: 'CFS.Core.BKOF/scripts/UpdateWorkItem.ps1'
      dependsOn: download_and_publish_excel_file
      workItemComment: "Failed to downloaded the input parameter file from work item: $(workItemId)"
      workItemId: $(workItemId)
      condition: eq(dependencies.download_and_publish_excel_file.result, 'Failed')
      workItemState: "To Do"
