parameters:

- name: serviceConnection
  type: string

steps:
- task: AzureKeyVault@2
  env:
     MyKeyValue: '$(sshKeyName)'
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }} # string. Alias: ConnectedServiceName. Required. Azure subscription. 
    KeyVaultName: '$(keyVaultName)'# string. Required. Key vault. 
    SecretsFilter: '$(sshKeyName)' # string. Required. Secrets filter. Default: *.
    RunAsPreJob: false # boolean. Required. Make secrets available to whole job. Default: false.

- task: PowerShell@2     
  inputs:
    targetType: 'inline' 
    script: |
      echo $env:MyKeyValue 

# - task: GraphEmail@0
#   displayName: 'Sending email using Graph Api'
#   inputs:
#     To: '' # The Business User who will receive the email 
#     From: 'svcCFSDataMigrationFactory@dev.cfs.com.au'
#     Subject: 'SSH Key for sFTP ' # Email Subject
#     Body: 'This is email test from automation pipeline.' # Email Body
#     BodyAsHtml: true
#     ShowClientSecret: false
#     ClientID: $(ClientID) 
#     ClientSecret: $(ClientSecret) 
#     TenantDomain: $(TenantDomain) 