parameters:
    stage: ''
    displayName: ''
    dependsOn: ''
    condition: ''
    pool: ''
    variableGroup: ''
    sendEmailDescription: ''
    emailSubject: ''
    emailBody: ''
    environment: ''
    receiverEmailAddress: ''

stages:
- stage: ${{ parameters.stage}}
  displayName: ${{ parameters.displayName}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  jobs:
  - template: sendemail.yml
    parameters:
      name: send_email
      displayName: ${{ parameters.sendEmailDescription}}
      pool: ${{ parameters.pool}}
      continueOnError: false
      emailSubject: ${{ parameters.emailSubject}}
      emailBody: ${{ parameters.emailBody}}
      environment: ${{ parameters.environment}}
      receiverEmailAddress: ${{ parameters.receiverEmailAddress}}
      condition: ''
      variableGroup: var-password
