parameters:
    stage: ''
    displayName: ''
    dependsOn: ''
    condition: ''
    name: ''
    description: ''
    pool: ''
    variableGroup: ''
    workItemId: ''
    workItemComment: ''
    workItemState: ''



stages:
- stage: ${{ parameters.stage}}
  displayName: ${{ parameters.displayName}}
  dependsOn: ${{ parameters.dependsOn}}
  condition: ${{ parameters.condition}}
  jobs:

  - template: updateworkitem.yml
    parameters:
      name: ${{ parameters.name}}
      displayName: ${{ parameters.description}}
      pool: ${{ parameters.pool}}
      continueOnError: false
      variableGroup: ${{ parameters.variableGroup}}
      scriptFilePath: 'CFS.Core.BKOF/scripts/UpdateWorkItem.ps1'
      workItemComment: ${{ parameters.workItemComment}}
      workItemId: ${{ parameters.workItemId}}
      workItemState: ${{ parameters.workItemState}}

