#deploy-KeyVault.yml

parameters:

- name: serviceId
  type: string

- name: serviceName
  type: string
  
- name: serviceConnection
  type: string

- name: deploymentType
  type: string

- name: subscriptionId
  type: string

- name: securitySubscriptionId
  type: string

- name: localAdminPassword
  type: string

- name: landingZoneType
  type: string

steps:
  - task: AzureCLI@2
    displayName : 'Add keyvault role assignment in ${{ parameters.serviceName }} Subscription'
    inputs:
      azureSubscription: '${{ parameters.serviceConnection }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(templateDirectory)\deploy-KeyVaultAuth.bicep `
                    --parameters subscriptionID='${{ parameters.subscriptionId }}' `
                    --parameters $(parameterDirectory)\05-Key-Vault\KeyVaultAuth-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json

  - task: AzureCLI@2
    displayName : 'Deploy Key Vault in ${{ parameters.serviceName }} Subscription'
    inputs:
      azureSubscription: '${{ parameters.serviceConnection }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: az deployment sub $(deploymentType) --location '$(resourceLocation)' `
                    --name $(deploymentName) `
                    --template-file $(templateDirectory)\deploy-KeyVault.bicep `
                    --parameters azureTenantId='$(azureTenantIdvar)' `
                    --parameters storageAccountSubscriptionId='$(securitySubscriptionId)' `
                    --parameters workspaceSubscriptionId='$(securitySubscriptionId)' `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)' `
                    --parameters localAdminPassword='${{ parameters.localAdminPassword }}' `
                    --parameters $(parameterDirectory)\05-Key-Vault\KeyVault-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json `
                    --parameters owner='$(Owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)'