#vm-deployment.yml

parameters:

- name: vmServiceName
  type: string

- name: subscriptionServiceId
  type: string
  
- name: serviceConnection
  type: string

- name: deploymentType
  type: string

- name: securitySubscriptionId
  type: string

- name: taskNumber
  type: string

- name: vmOSType
  type: string

- name: vmLocation
  type: string

- name: keyVaultName
  type: string

- name: vmDeploymentType
  type: string

steps:
  - task: AzureCLI@2
    displayName : Deploy ${{ parameters.vmServiceName }} Virtual Machine in ${{ parameters.subscriptionServiceId }} Subscription
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: | 
                    "Starting az deployment"
                    az deployment sub $(deploymentType) --location 'australiaeast' `
                    --name $(deploymentName) `
                    --template-file $(System.ArtifactsDirectory)\bicep-templates\deployment\deployment-templates\deploy-tempvm.bicep `
                    --parameters $(System.ArtifactsDirectory)\bicep-templates\deployment\03-TempVM\tempvm-${{ parameters.serviceId }}.param.$(AzureEnvironmentPrefix).json `
                    --parameters adminpassword=$(adminPassword) `
                    --parameters owner='$(Owner)' `
                    --parameters costCenter='$(costCenterCode)' `
                    --parameters australiaEastOffsetSymbol='$(AustraliaEastOffsetSymbol)' `
                    --parameters environmentPrefix='$(AzureEnvironmentPrefix)'